version: '2'

services:
  app:
    "ports":
      - 20193:8080
    image: apijar/compose
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app3
    external_links:
      -
    depends_on:
      - db3
    env_file:
      - docker/web-variables.env

  db3:
    image: 'postgres:13.1-alpine'
    ports:
      - 30193:5432
    container_name: db3
    restart: always
    env_file:
      - docker/db-variables.env