spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      platform: postgres
app:
  tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
  tokenExpirationMsec: 864000000
  API_KEY: ${API_KEY}
  authorizedRedirectUris:
    - https://bwell-frontend.herokuapp.com/