spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO}
      generate-ddl: ${SPRING_JPA_HIBERNATE_GENERATE_DDL}
  datasource:
    jdbc-url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver

app:
  tokenSecret: ${APP_TOKEN_SECRET}
  tokenExpirationMsec: 864000000
  API_KEY: ${API_KEY}
  shouldCreate: ${SHOULD_CREATE:true}
  corsOrigin: ${FRONTEND_HOST:https://bwell-frontend.herokuapp.com/}
  authorizedRedirectUris:
    - ${AUTH_REDIRECT_URI:https://bwell-frontend.herokuapp.com/oauth2/redirect}