spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 732455086497-tse2q35l4cqqs2kat2qv2td1fc6odj47.apps.googleusercontent.com
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}